spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql

  mail:
    host: smtp.gmail.com
    port: 587
    username: pawel.lukaszewicz99@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


